{% set name = "datajoint" %}
{% set version = "0.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5dbf0384fe1e767077f41428f2d3547d166637716ba1faed688752eec836253c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - minio
    - pyparsing
    - networkx
    - pymysql >=0.7.2
    - ipython
    - numpy
    - tqdm
    - pandas
    - pydot
    - matplotlib-base
    - graphviz
    - mscorefonts
    - pyttk

test:
  imports:
    - datajoint
  commands:
    # check that erd drawing is supported
    - python -c 'import datajoint as dj; assert dj.diagram.diagram_active'

about:
  home: https://datajoint.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: A relational data framework for scientific data pipelines with MySQL backend.

  description: |
    DataJoint for Python is a high-level programming interface for relational databases
    designed to support data processing chains in science labs. DataJoint is built on the
    foundation of the relational data model and prescribes a consistent method for
    organizing, populating, and querying data.
  doc_url: https://docs.datajoint.io
  dev_url: https://github.com/datajoint/datajoint-python

extra:
  recipe-maintainers:
    - tjd2002
    - guzman-raphael
    - eywalker
    - dimitri-yatsenko
    - ixcat
