{% set name = "datajoint" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 679d5762715c5e99cc70112e53d035e62f8a71de374ae5622f27ad5bb91567c2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - minio
    - pyparsing
    - networkx
    - pymysql >=0.7.2
    - ipython
    - numpy
    - tqdm
    - pandas
    - pydot
    - matplotlib-base
    - graphviz
    - mscorefonts
    - pyttk

test:
  imports:
    - datajoint
  commands:
    # check that erd drawing is supported
    - python -c 'import datajoint as dj; assert dj.diagram.diagram_active'

about:
  home: https://datajoint.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'A relational data framework for scientific data pipelines with MySQL backend.'

  description: |
    DataJoint for Python is a high-level programming interface for relational databases
    designed to support data processing chains in science labs. DataJoint is built on the
    foundation of the relational data model and prescribes a consistent method for
    organizing, populating, and querying data.
  doc_url: https://docs.datajoint.io
  dev_url: https://github.com/datajoint/datajoint-python

extra:
  recipe-maintainers:
    - tjd2002
    - guzman-raphael
