{% set name = "datajoint" %}
{% set version = "2.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df93441640d86215bc8276b8cc8852f3dd55430588bd89689c82de36be0e2f11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dj = datajoint.cli:cli
    - datajoint = datajoint.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<3.14
    - numpy
    - packaging
    - pymysql >=0.7.2
    - deepdiff
    - pyparsing
    - pandas
    - tqdm
    - networkx
    - pydot
    - fsspec >=2023.1.0
    - pydantic-settings >=2.0.0
    ## System Dependencies
    # for dj.Diagram
    - graphviz

test:
  requires:
    - python {{ python_min }}
  imports:
    - datajoint
  commands:
    # check that Diagram is supported
    - python -c 'import datajoint as dj; assert dj.diagram.diagram_active'
    # check graphviz is installed
    - dot -V
    # check CLI entry points
    - dj --help
    - datajoint --help

about:
  home: https://datajoint.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A relational data framework for scientific data pipelines.

  description: |
    DataJoint for Python is a framework for scientific workflow management based on relational principles.
    DataJoint is built on the foundation of the relational data model and prescribes a consistent method for
    organizing, populating, computing, and querying data.
  doc_url: https://docs.datajoint.com/
  dev_url: https://github.com/datajoint/datajoint-python

extra:
  recipe-maintainers:
    - dimitri-yatsenko
    - datajointbot
    - ttngu207
