{% set name = "datajoint" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e55538cacf9f263dc77d1d636d1d14fdeb5531adceeb5b8b9af56c4ec9a4f00

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - otumat
  run:
    - python >=3.8
    - minio >=7.0.0
    - pyparsing
    - networkx
    - pymysql >=0.7.2
    - ipython
    - numpy
    - tqdm
    - pandas
    - pydot
    - matplotlib-base
    - graphviz
    - mscorefonts
    - pyttk
    - cryptography
    - otumat
    - urllib3

test:
  imports:
    - datajoint
  commands:
    # check that erd drawing is supported
    - python -c 'import datajoint as dj; assert dj.diagram.diagram_active'

about:
  home: https://datajoint.com
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: A relational data framework for scientific data pipelines.

  description: |
    DataJoint for Python is a framework for scientific workflow management based on relational principles.
    DataJoint is built on the foundation of the relational data model and prescribes a consistent method for
    organizing, populating, computing, and querying data.
  doc_url: https://datajoint.com/docs/core/datajoint-python/latest/
  dev_url: https://github.com/datajoint/datajoint-python

extra:
  recipe-maintainers:
    - guzman-raphael
    - dimitri-yatsenko
    - jverswijver
    - A-Baji
    - zitrosolrac
    - datajointbot
    - yambottle
