travis:
  secure:
    BINSTAR_TOKEN: XWwTKdP/K9XQHzZR4cNfdwODHjTPqsMMYrQJtKIpIee9vA/DEDW/FtuLBonvTI9AMa2cAULx4aT9/tL5bXgbp7m1ETA7gLa6E2v8JpB70KzqLYNgGmlifM+cvVI6Mu0neU4RVZhrcyYe8sNOgX8Bn1MGx2K6tMctuCl2uXGi9mfzCw4sunbyB1ZFIY7IIP/Rq3iYJgnU6taWJvoqMV20HHkGqhyBmVPWljZoQ9Hj8Uu3pr8XR5ScH23MBGg5zuI5DX7iWupz8Wtl2Hf6OZOYe+kdSKsnAbXW9ChjK68X5SPP/vZ6rsTWoo/yVFKlXHj/RNDc0MsysqQ+uKhT6leDSYMFveiuo7LEc5OSrmKbGGSSn38HSuMQk/1t/qVStfnyVPjvypJ2RoRsyevO38Ol0YCerslAzFKYVQOjAsfvQGnphwsrGeIFP9kValeJjuKKyeKgkQV3FnNVmKfZPIDGaW1esK3481Gq5HV68edkSmP3V+MvQ7/zGnKEdcmpIGqks4CUR1A9uQhRe5HDRLbA9whkNyROa6L8rtGjX0IduaUeMkDEJlGTAI9uPuGLuvLC4iGGTUh3Hnfg4Q0zmuivHpWbTEITDMrZpp4DvkXohWJi85UuKjKGICWwmOup3M65RYB/StB9vTFDDxk1ZtvGRLrtYF6Q17HQXBjg8/0v3fY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
